[tool.poetry]
name = "pyise-ers"
version = "0.3-dev"
description = "ISE-ERS API Wrapper"
authors = ["Falk <falk@mockel.se>"]
license = "GPL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "*"
furl = "*"


[tool.poetry.group.dev.dependencies]
flake8 = "*"
pytest = "*"
black = "*"
pytest-cov = "*"
ptpython = "*"
codecov = "*"
setuptools = "^67.7.2"
twine = "^4.0.2"
wheel = "^0.40.0"
isort = "^5.12.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
