# Inspired by https://github.com/JonasKs/django-guid/blob/master/.github/workflows/publish_to_pypi.yml
name: Publish ise to PyPI and TestPyPI 📦

on: push

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-publish-pypi.txt
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish distribution of ise to Test PyPI 📦
      # If it's a push, and the push includes a tag with `-rc` in it, release to TestPyPi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && contains(github.ref, '-rc')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution of ise to PyPI 📦
      # If it's a push, and the push does _not_ contain `-rc` in it, release to production PyPi
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && !contains(github.ref, '-rc')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
